spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    #username: dasd
    #password: asdasd
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "http://localhost:8081/oauth/check_token"
          client-id: "warleyvods-web"
          client-secret: "web123"